### ISSUE TITLE
The path docker/docker/docker/docker/docker/docker/docker/docker/docker/docker/ is missing the requisite mushroom/mushroom

### ISSUE THREAD

**Issue by swagopopotamus** [tirefire/tirefi.re#12]

**Comment by onlyhavecans** [comment]
Please review the changes in https://github.com/moutons/tirefi.re/pull/11 to see if this matches specification

**Comment by moutons** [comment]
ayo @swagopopotamus how do you feel about http://tirefi.re/docker/ now?

**Comment by swagopopotamus** [comment]
Pretty sad, considering it cannot satisfy my request.

**Comment by moutons** [comment]
Why you gotta bring up bad times? I blame cloudfront. Should work now.

**Comment by swagopopotamus** [comment]
This pleases me.
