### ISSUE TITLE
need a /dependabot

### ISSUE THREAD

**Issue by jtimberman** [tirefire/tirefi.re#121]

**Comment by aditirao7** [comment]
Can I take up this issue?

**Comment by jjasghar** [comment]
The tirefire burns in anyones heart that is willing to help.

**Comment by aditirao7** [comment]
> The tirefire burns in anyones heart that is willing to help.

Haha I'll get started right away then! :star_struck:

**Comment by moutons** [comment]
idk about closing it, someone could do a redirect (or better, an iframe page at /dependabot) to https://github.com/tirefire/tirefi.re/pulls/app%2Fdependabot
