### ISSUE TITLE
To Template or not to Template?

### ISSUE THREAD

**Issue by moutons** [tirefire/tirefi.re#29]
updating HUMANS.txt and other common page elements will be easier using templating. I got most things ready on a Jekyll branch that I need to push up from the other computer, but I'm not sure that I want to use Jekyll. Thoughts from @tirefire/tirefire-hugopserati @tirefire/cheslocks ? HAML? ERB? heredocs?

**Comment by filler** [comment]
Why not use Jekyll?  It works, people know it.  Kind of like CFEngine.

**Comment by moutons** [comment]
0b23ba12c70cf424f2c2bd0275cf0da1a5b6b4ae closes this 🎈
